spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://localhost:3306/upi_central
    username: root
    password: Manik@231896

bank:
  a:
    url: http://localhost:8081
  b:
    url: http://localhost:8082

